"""
HA Print Center
First Page Example
"""

from ha_print_center.document import Document
from ha_print_center.renderer import DebugRenderer


def main():
    document = Document()

    document.add_title(
        "HA Print Center"
    )

    document.add_subtitle(
        "The First Page"
    )

    document.add_text(
        "Home Assistant document engine online."
    )

    document.add_text(
        "IPP printer connection verified."
    )

    document.add_footer(
        "Generated by Home Assistant"
    )

    renderer = DebugRenderer()

    output = renderer.render(document)

    print(output)


if __name__ == "__main__":
    main()
