"""
Home Assistant integration helpers
for HA Print Center.
"""

from .document import Document
from .renderer import DebugRenderer


def create_test_page():
    """
    Create the first HA Print Center test page.
    """

    document = Document()

    document.add_title(
        "HA Print Center"
    )

    document.add_subtitle(
        "The First Page"
    )

    document.add_text(
        "Home Assistant document engine online."
    )

    document.add_footer(
        "Generated by HA Print Center"
    )

    renderer = DebugRenderer()

    return renderer.render(document)
